# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - Dependabot
  categories:
    - title: New Features 🎉
      labels:
        - newfeature
    - title: General Changes
      labels:
        - "*"
