services:
  planner-dev:
    container_name: planner-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
      POSTGRES_DB: planner_db
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - internal

    command: sh -c "npm install --silent && npx prisma migrate dev --name init && npx prisma generate && npm run dev "

  planner-prisma-studio:
    container_name: planner-prisma-studio
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
      POSTGRES_DB: planner_db
    env_file:
      - .env
    ports:
      - 1111:1111
    networks:
      - internal

    command: sh -c "npx prisma studio -p 1111 -n 0.0.0.0"

  planner-db-dev:
    container_name: planner-db-dev
    image: postgres:16.4-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: planner_db
    networks:
      - internal
    volumes:
      - ./postgres:/var/lib/postgresql/data

  planner-pgadmin-dev:
    image: dpage/pgadmin4
    container_name: planner-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

networks:
  internal:
