services:
  schedulerv2:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
      DATABASE_URL: "postgresql://postgres:example@postgres:5432/scheduler_db"
      POSTGRES_DB: scheduler_db
      #KEYCLOAK_ID: "rsdv2"
      #KEYCLOAK_ISSUER: "https://auth.sccs.swarthmore.edu/realms/master"
      #NEXTAUTH_URL: "http://localhost:3000"
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - internal
    command: sh -c "npm install --silent && npx prisma migrate dev && npm run dev "

  postgres:
    image: postgres:16.4-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: scheduler_db
    networks:
      - internal
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  internal:
