-- AlterTable
ALTER TABLE "Rating" 
ADD COLUMN IF NOT EXISTS "isRMP" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "rmpProfId" TEXT,
ADD COLUMN IF NOT EXISTS "rmpLink" TEXT,
ADD COLUMN IF NOT EXISTS "rmpDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "tags" TEXT;

